package dev.provenance.recorder.activation

import com.intellij.openapi.project.Project
import com.intellij.openapi.project.guessProjectDir
import com.intellij.openapi.roots.ProjectRootManager
import com.intellij.openapi.vfs.VirtualFile
import dev.provenance.core.Manifest

/** One verified assignment root discovered under the project. */
data class DiscoveredManifest(val root: VirtualFile, val manifest: Manifest)

/**
 * Directory names discovery never descends into: heavy, irrelevant, or (for `.provenance` /
 * `.idea`) generated by the recorder or IDE itself, mirroring RecordabilityFilter's
 * IDE_SETTINGS_DIR_NAME exclusion generalized to a walk that runs before any session (and its
 * one fixed provenanceDir) exists.
 */
val DISCOVERY_PRUNED_DIR_NAMES: Set<String> = setOf(
    ".git", ".provenance", ".idea", ".gradle", "node_modules", "build", "out", "target", "dist",
)

/** Bounds cost on deep/large trees. Five levels comfortably covers realistic course layouts
 * (e.g. `61a/proj/cats/` is 3 deep from a `61a/` search root). */
const val DEFAULT_MAX_DISCOVERY_DEPTH: Int = 6

/**
 * Recursively find every directory under [searchRoots] holding a verified `.provenance-manifest`
 * / `provenance-manifest`, skipping [prunedDirNames] and anything past [maxDepth]. Reuses the
 * existing, unmodified [loadAndVerifyManifest] per directory — an unparsable or bad-signature
 * manifest is silently skipped (PRD §4.1: "the extension does nothing"), never throws, never
 * partially activates. Continues descending into a directory that already holds a verified
 * manifest, so a genuinely nested assignment-inside-an-assignment is still discovered; any
 * resulting overlap is resolved by nearest-ancestor ownership at routing time, not here.
 */
fun discoverManifestRoots(
    searchRoots: List<VirtualFile>,
    coursePubkeyHex: String = COURSE_PUBLIC_KEY_HEX,
    maxDepth: Int = DEFAULT_MAX_DISCOVERY_DEPTH,
    prunedDirNames: Set<String> = DISCOVERY_PRUNED_DIR_NAMES,
): List<DiscoveredManifest> {
    val found = mutableListOf<DiscoveredManifest>()
    val visited = mutableSetOf<String>()
    for (searchRoot in searchRoots) {
        walk(searchRoot, depth = 0, maxDepth, prunedDirNames, visited) { dir ->
            val result = loadAndVerifyManifest(dir, coursePubkeyHex)
            if (result is ManifestActivation.Active) {
                found += DiscoveredManifest(dir, result.manifest)
            }
        }
    }
    return found
}

private fun walk(
    dir: VirtualFile,
    depth: Int,
    maxDepth: Int,
    prunedDirNames: Set<String>,
    visited: MutableSet<String>,
    onDir: (VirtualFile) -> Unit,
) {
    if (!dir.isDirectory) return
    if (!visited.add(dir.path)) return
    onDir(dir)
    if (depth >= maxDepth) return
    for (child in dir.children) {
        if (child.isDirectory && child.name !in prunedDirNames) {
            walk(child, depth + 1, maxDepth, prunedDirNames, visited, onDir)
        }
    }
}

/**
 * Project-level convenience: search the guessed project dir plus every content root (covers
 * both the common single-content-root course project and a multi-module/attached-modules
 * layout) without requiring every consumer to assemble the search-root list by hand.
 */
fun discoverManifestRoots(project: Project, coursePubkeyHex: String = COURSE_PUBLIC_KEY_HEX): List<DiscoveredManifest> {
    val roots = LinkedHashSet<VirtualFile>()
    project.guessProjectDir()?.let { roots += it }
    roots += ProjectRootManager.getInstance(project).contentRoots
    return discoverManifestRoots(roots.toList(), coursePubkeyHex)
}
